# Example Configuration for simple-config-app (config.yaml)
server:
  port: 9091 # Different from SDK default
  mode: "debug"

log:
  level: "debug" # Changed to debug for better demo
  format: "text"  # Changed to json to show structured stacktrace
  outputPaths:
    - "stdout"
  enableColor: true # Keep true, though JSON won't show colors
  name: "simple-config-app"
  contextKeys:
    - "myCustomKey"
    - "user_id"
  maxSize: 10
  maxBackups: 1
  maxAge: 1
  compress: false

database:
  host: "example-db-host"
  user: "appuser"
  dbName: "app_db"

# Include a custom section for this app
customFeature:
  apiKey: "app-specific-key-from-file"
  rateLimit: 500
  enabled: true 